# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 'TKOaly/rv-client'
      uses: actions/checkout@v2
    - name: Checkout repository 'TKOaly/rv-backend'
      uses: actions/checkout@v2
      with:
        repository: TKOaly/rv-backend
        ref: develop
        token: ${{ secrets.GH_PAT }}
        path: backend
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Install Gulp
      run: npm i -g gulp-cli
    - run: gulp build
